### ISSUE TITLE
Shim tracing appears to be broken

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/shim#148]
See https://github.com/kata-containers/tests/issues/1255#issuecomment-469418931

**Comment by jodh-intel** [comment]
Grr - this gets me every time! The problem is that you *must* run docker with `--net none` to avoid that error. User error so closing...

**Comment by grahamwhaley** [comment]
Heh - any way we can make it detect the problem and report out more clearly?

**Comment by jodh-intel** [comment]
Not easily - see https://github.com/kata-containers/tests/issues/1255#issuecomment-470072205.
