### ISSUE TITLE
Error in golangci-lint

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/shim#164]
While running `GL_TEST_RUN=1 ./golangci-lint run -v` , we have the following error
```
15:17:04 make: 'kata-shim' is up to date.
15:17:04 INFO: Running golangci-lint checks on the following packages:
15:17:04 
15:17:04 github.com/kata-containers/shim
15:17:04 
15:17:04 INFO: Package paths:
15:17:04 
15:17:04 /tmp/jenkins/workspace/kata-containers-shim-ubuntu-18-04-master/go/src/github.com/kata-containers/shim
15:17:07 agent_test.go:93:19: composites: `github.com/kata-containers/shim/vendor/github.com/kata-containers/agent/protocols/grpc.Box` composite literal uses unkeyed fields (govet)
15:17:07 			ConsoleSize:  &pb.Box{10, 10},
15:17:07 			               ^
15:17:09 Build step 'Execute shell' marked build as failure
```
/ cc @ganeshmaharaj 

See: http://jenkins.katacontainers.io/job/kata-containers-shim-ubuntu-18-04-master/11/console

**Comment by ganeshmaharaj** [comment]
@GabyCT Seems like recently agent updated it's vendor repository for opencontainers https://github.com/kata-containers/agent/commit/39696c07e46a6600361462924d945df84775629b and that is causing two sets of issues. One in agent and this one which cascades from shim vendoring agent.

**Comment by GabyCT** [comment]
thanks @ganeshmaharaj
