### ISSUE TITLE
Rely on SIGUSR1 signal to signal the shim to connect

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/shim#27]
This might be a temporary solution, but this is the easiest way to make sure we can start the shim any time in order to get the PID, and that we can really control when to make him connect the proxy/agent.

**Comment by bergwolf** [comment]
hi @sboeuf, what is the issue with current no SIGUSR1 approach and why it cannot be fixed?

**Comment by sboeuf** [comment]
Well in order to make this work without the SIGUSR1 signal, we would need to create and start the sandbox + create the container from the `runtime create` because the shim needs to be started during the create and at the same time the shim needs the sandbox, the container and the process to be created inside the agent.
I am not saying this is not doable but for now, as we're trying to connect all the pieces with virtcontainers, having this signal is more convenient to make sure we can prevent the shim from connecting the agent directly after we start it.
I am asking for this as a temporary solution, while I can reorganize virtcontainers code, and in the meantime I can work on making sure everything works well together.

**Comment by laijs** [comment]
Did you mean that virtcontainers might start the shim before finishing creating the container or even before finishing starting the sandbox? I don't think it's a good idea.

**Comment by sboeuf** [comment]
@laijs yes that's what I meant and I agree it's not ideal. That's why yesterday, I have been reorganizing virtcontainers code a bit in order to make this right. I have been able to make the whole chain working but I need to clean my patches.
I don't think I will need SIGUSR1 support after all (even as a temporary solution).

**Comment by bergwolf** [comment]
The shim can connect to agent at any time and both runv and cc-runtime handle it properly now. Closing.
