### ISSUE TITLE
github: Remove issue template and use central one

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/shim#270]
Remove the GitHub issue template from this repository. We already have a
central set of templates [1] that are being used so the template in this
repository is redundant.

[1] - https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE/

**Comment by c3d** [comment]
Not sure from the comment on the top-level one if you need to remove it or not in the end.

**Comment by jodh-intel** [comment]
The template removal PRs are not "essential" because since we have defined a top-level template at https://github.com/kata-containers/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md for example, if you go to https://github.com/kata-containers/shim/issues/new/choose and click "bug", you'll see the template from https://github.com/kata-containers/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md, **not** the template this PR removes :smile:
