### ISSUE TITLE
Apply user, group and perms to install files

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/shim#29]
Rather than just calling `install -D` in `Makefile`, call:

```
INSTALL_USER = root
INSTALL_GROUP = root
INSTALL_MODE = 0644

    :

install:
    install --owner="$(INSTALL_USER)" --group="$(INSTALL_GROUP)" --mode="$(INSTALL_MODE)" -D ...
```

The minimum set of permissions should be applied in all cases. This issue applies to `shim`, `runtime`, `proxy` and `agent`.

See: https://github.com/kata-containers/shim/pull/24#pullrequestreview-88649198

**Comment by egernst** [comment]
We should stanardize this throughout. I agree re: need still.
