### ISSUE TITLE
nsenter support

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/shim#44]
In docker case, a container can join the network namespace of another container. In runv, we solved it by letting `runv shim` own the network namespace and if a new container needs to enter the netns, we make its shim join the netns.

@sameo @sboeuf how does cc-runtime support the case?

**Comment by egernst** [comment]
@bergwolf -- can you clarify, do you mean via something like:
  `docker run --net=container:existingcontainer`?

**Comment by bergwolf** [comment]
This is handled by runv and virtcontainers now. Closing.
