### ISSUE TITLE
Reduce footprint by implementing shim with other language

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/shim#83]
The shim represents the container process on the host side. And for this reason, we have one shim per process, meaning we'll have one shim for the container process, but we'll also have one for every `exec` on an existing container.
If you look at this from a k8s perspective, we might have a lot of containers and associated processes inside a pod, raising the density per pod.

In order to improve density, we should consider re-writing the shim in a lighter weight language leveraging some dynamically loaded libraries by writing it in C or Rust.

The constraint is to make sure we would rely on a solid gRPC library as we don't want to maintain our own, and try to catch up with changes along the time.

**Comment by jcvenegas** [comment]
Seems that C and rust has not official support for grpc, depending on our needs we could check if the creates for grpc support in rust are enough for our use cases.

An alternative is that we could use c++ that has official grpc support.

**Comment by sboeuf** [comment]
Yes, but I was wondering if relying on what they call the `shared C core library` could work or if this is too low level to be re-used directly.

**Comment by grahamwhaley** [comment]
Well, C++ doesn't have to be less efficient than C - it very much depends on how they've constructed the C++ lib and then how one uses it. I suspect a carefully written C++ shim would be find. It needs a little eval most likely.

**Comment by sboeuf** [comment]
As a note from the Arch committee meeting, one first step in reducing the footprint of the shim might be to rely on `ttrpc` which is compliant with `gRPC`.
But this solves only part of the problem since Golang does not fit low footprint binaries.

**Comment by sboeuf** [comment]
@kata-containers/shim feel free to assign this to yourself if interested in working on this.

**Comment by jodh-intel** [comment]
Right. I do think rust is probably the right long-term solution here as it hits the sweetspot between performance, security and (probably) memory footprint. However, official grpc support seems to be in-progress/stalled: https://github.com/grpc/grpc/issues/9316.

**Comment by gnawux** [comment]
Actually I think the shim-less is better than shims in any language, and It would be better try contribute to containerd plugin and cri-O to support kata-lib + built-in shim

**Comment by sboeuf** [comment]
@gnawux sure, it makes sense to look at those possibilities. But until then, it would be great to propose a better version of our pure OCI support. And this means a better footprint regarding the shim.
