### ISSUE TITLE
Support darwin build for kata shim

### ISSUE THREAD

**Issue by raravena80** [kata-containers/shim#86]
# Description of problem

Opening up to track building the Kata Shim on macos. Needed to support Kata Containers over xhyve

# Expected result

```
$ cd $GOPATH/src/github.com/kata-containers/shim && make
go build -o kata-shim -ldflags "-X main.version=1.0.0-a69326b63802952b14203ea9c1533d4edb8c1d64"
# Builds the kata-shim exec on darwin
```

# Actual result

```
$ cd $GOPATH/src/github.com/kata-containers/shim && make
go build -o kata-proxy -ldflags "-X main.version=1.0.0-a69326b63802952b14203ea9c1533d4edb8c1d64"
# github.com/kata-containers/shim
./signals.go:27:2: undefined: syscall.SIGSTKFLT
make: *** [kata-proxy] Error 2
```
---

**Comment by jodh-intel** [comment]
Yes, we could create a `signals_darwin.go`. All it would need to contain is the darwin-specific `handledSignalsMap`. Or we could make the file even smaller by requiring that each arch-specific signals file define `archSignalsMap [map][syscall.Signal]bool` which for darwin might be empty.

But looking again at the man pages, it appears the kernel never sends `SIGSTKFLT`, so the simplest fix might be to just remove `SIGSTKFLT` entirely. Is that sufficient to allow a darwin build?

**Comment by raravena80** [comment]
@jodh-intel yep, that's enough

**Comment by raravena80** [comment]
@jodh-intel actually there's more. The `terminal_linux.go` is specific to Linux. I'll submit a PR and we can iterate.
